import ZohoContextProvider from "@/components/app-providers";
import GoogleAPIProvider from "@/components/google-api-providers";
import type { Metadata } from "next";
import { Roboto } from "next/font/google";
import Script from "next/script";
import { Toaster } from "react-hot-toast";
import "./globals.css";

const roboto = Roboto({
  variable: "--font-roboto",
  subsets: ["latin"],
  weight: ["400", "500", "700"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <head>
        <Script
          src="https://live.zwidgets.com/js-sdk/1.2/ZohoEmbededAppSDK.min.js"
          strategy="beforeInteractive"
        />
      </head>
      <body className={`${roboto.variable} antialiased`}>
        <GoogleAPIProvider>
          <ZohoContextProvider>{children}</ZohoContextProvider>
        </GoogleAPIProvider>
        <Toaster />
      </body>
    </html>
  );
}
